name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Use GitHub Secret
        run: |
          echo "GitHub Event: ${{ secrets.TOKEN }}"
          echo "GitHub Event: ${{ secrets.GH_PAT }}"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14 # Change this to the Node.js version you need

      - name: Installing NPM packages
        run: npm install --force

      - name: Building project
        run: npm run build

      - name: Testing project
        run: npm run test

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Set up Git
        run: |
          git config user.name "shania873"
          git config user.email "vanaeca@hotmail.com"

      - name: Checkout gh-pages branch
        run: git checkout -b gh-pages origin/gh-pages

      - name: Copy build files to gh-pages branch
        run: cp -r ./build/* .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update gh-pages with production build"
          git push origin gh-pages
